-- FINAL V3 MODEL — custom application authentication (username + password)
-- This migration replaces the V2 Supabase-Auth-linked model.
-- IMPORTANT: it resets V2 business/test data. auth.users is not used and is not modified.

begin;

create extension if not exists pgcrypto;

-- Remove V2 functions.
drop function if exists public.confirm_participation_delta(uuid, integer, uuid, text);
drop function if exists public.heartbeat_observer(uuid, text);
drop function if exists public.confirm_party_result(uuid, integer, uuid);
drop function if exists public.request_result_correction(uuid, integer, text);
drop function if exists public.resolve_result_correction(uuid, boolean);
drop function if exists public.set_election_mode(text);
drop function if exists public.current_app_user_id();
drop function if exists public.is_regional_admin();

-- Remove previous business model. auth.users is intentionally untouched.
drop table if exists public.user_sessions cascade;
drop table if exists public.result_corrections cascade;
drop table if exists public.party_results cascade;
drop table if exists public.observer_presence cascade;
drop table if exists public.participation_events cascade;
drop table if exists public.participation_counters cascade;
drop table if exists public.audit_logs cascade;
drop table if exists public.users cascade;
drop table if exists public.regional_settings cascade;
drop table if exists public.app_settings cascade;
drop table if exists public.local_bureaus cascade;
drop table if exists public.regional_offices cascade;

-- Legacy V1 names, in case the database skipped V2 cleanup.
drop table if exists public.observer_assignments cascade;
drop table if exists public.profiles cascade;
drop table if exists public.polling_stations cascade;
drop table if exists public.polling_centers cascade;
drop table if exists public.constituencies cascade;
drop table if exists public.regions cascade;

drop type if exists public.app_role cascade;
drop type if exists public.result_status cascade;
drop type if exists public.election_mode cascade;

create type public.app_role as enum ('OBSERVER', 'REGIONAL_ADMIN');
create type public.result_status as enum ('CONFIRMED', 'CORRECTION_PENDING', 'CORRECTED');
create type public.election_mode as enum ('PREPARATION', 'VOTING', 'COUNTING', 'COMPLETED');

create table public.regional_offices (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  region_label text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.regional_settings (
  regional_office_id uuid primary key references public.regional_offices(id) on delete cascade,
  election_mode public.election_mode not null default 'PREPARATION',
  orange_minutes integer not null default 5 check (orange_minutes between 1 and 120),
  red_minutes integer not null default 15 check (red_minutes between 2 and 240),
  updated_at timestamptz not null default now(),
  constraint red_after_orange check (red_minutes > orange_minutes)
);

create table public.local_bureaus (
  id uuid primary key default gen_random_uuid(),
  regional_office_id uuid not null references public.regional_offices(id) on delete restrict,
  code text not null,
  name text not null,
  address text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (regional_office_id, code),
  unique (id, regional_office_id)
);
create index local_bureaus_office_idx on public.local_bureaus(regional_office_id, active, code);

-- Application users only. They are NOT PostgreSQL users and are NOT Supabase Auth users.
-- The password is stored only as a one-way bcrypt hash generated by the backend.
create table public.users (
  id uuid primary key default gen_random_uuid(),
  regional_office_id uuid not null references public.regional_offices(id) on delete restrict,
  username text not null,
  password_hash text not null,
  full_name text not null,
  email text,
  phone text,
  role public.app_role not null,
  local_bureau_id uuid,
  active boolean not null default true,
  must_change_password boolean not null default false,
  failed_login_count integer not null default 0 check (failed_login_count >= 0),
  locked_until timestamptz,
  last_login_at timestamptz,
  password_changed_at timestamptz,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint username_format check (username ~ '^[A-Za-z0-9._-]{3,60}$'),
  constraint observer_requires_bureau check (
    (role = 'OBSERVER' and local_bureau_id is not null)
    or (role = 'REGIONAL_ADMIN' and local_bureau_id is null)
  ),
  constraint users_bureau_same_office_fk
    foreign key (local_bureau_id, regional_office_id)
    references public.local_bureaus(id, regional_office_id)
    on delete restrict
);
create unique index users_username_ci_uq on public.users(lower(username));
create index users_office_role_idx on public.users(regional_office_id, role, active);
create index users_local_bureau_idx on public.users(local_bureau_id);

-- Core business rule: at most one ACTIVE observer can be assigned to a local bureau.
create unique index one_active_observer_per_local_bureau
  on public.users(local_bureau_id)
  where role = 'OBSERVER' and active = true;

create table public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_seen_at timestamptz not null default now(),
  user_agent text,
  created_at timestamptz not null default now()
);
create index user_sessions_user_active_idx on public.user_sessions(user_id, expires_at desc) where revoked_at is null;

create table public.participation_counters (
  local_bureau_id uuid primary key references public.local_bureaus(id) on delete cascade,
  current_count integer not null default 0 check (current_count >= 0),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.users(id) on delete set null
);

create table public.participation_events (
  id uuid primary key default gen_random_uuid(),
  operation_uuid uuid not null unique,
  local_bureau_id uuid not null references public.local_bureaus(id) on delete restrict,
  observer_id uuid not null references public.users(id) on delete restrict,
  previous_value integer not null check (previous_value >= 0),
  delta integer not null check (delta <> 0),
  new_value integer not null check (new_value >= 0),
  device_id text,
  created_at timestamptz not null default now(),
  server_timestamp timestamptz not null default clock_timestamp()
);
create index participation_events_bureau_created_idx on public.participation_events(local_bureau_id, created_at desc);
create index participation_events_observer_created_idx on public.participation_events(observer_id, created_at desc);

create table public.observer_presence (
  observer_id uuid primary key references public.users(id) on delete cascade,
  local_bureau_id uuid not null unique references public.local_bureaus(id) on delete cascade,
  last_seen_at timestamptz not null default now(),
  connection_status text not null default 'CONNECTED'
    check (connection_status in ('CONNECTED','OFFLINE','BACKGROUND')),
  updated_at timestamptz not null default now()
);
create index observer_presence_last_seen_idx on public.observer_presence(last_seen_at desc);

create table public.party_results (
  id uuid primary key default gen_random_uuid(),
  operation_uuid uuid not null unique,
  local_bureau_id uuid not null unique references public.local_bureaus(id) on delete restrict,
  observer_id uuid not null references public.users(id) on delete restrict,
  votes integer not null check (votes >= 0),
  status public.result_status not null default 'CONFIRMED',
  submitted_at timestamptz not null default now(),
  confirmed_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index party_results_status_idx on public.party_results(status);

create table public.result_corrections (
  id uuid primary key default gen_random_uuid(),
  result_id uuid not null references public.party_results(id) on delete restrict,
  old_value integer not null check (old_value >= 0),
  proposed_value integer not null check (proposed_value >= 0),
  reason text not null check (char_length(trim(reason)) between 3 and 1000),
  requested_by uuid not null references public.users(id) on delete restrict,
  validated_by uuid references public.users(id) on delete restrict,
  status text not null default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create unique index one_pending_correction_per_result
  on public.result_corrections(result_id)
  where status = 'PENDING';

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  regional_office_id uuid not null references public.regional_offices(id) on delete restrict,
  user_id uuid references public.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index audit_logs_office_created_idx on public.audit_logs(regional_office_id, created_at desc);
create index audit_logs_user_created_idx on public.audit_logs(user_id, created_at desc);
create index audit_logs_action_created_idx on public.audit_logs(action, created_at desc);

-- -------------------------------------------------------------------------
-- Atomic business functions. The backend supplies the authenticated user id;
-- functions re-check role, activity, bureau assignment and regional scope.
-- Frontend/anon/authenticated roles will not be allowed to execute them.
-- -------------------------------------------------------------------------

create or replace function public.confirm_participation_delta(
  p_user_id uuid,
  p_delta integer,
  p_operation_uuid uuid,
  p_device_id text default null
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users;
  v_old integer;
  v_new integer;
  v_existing integer;
  v_mode public.election_mode;
begin
  if p_delta = 0 then raise exception 'delta cannot be zero'; end if;
  if abs(p_delta) > 10000 then raise exception 'delta out of range'; end if;

  select * into v_user
  from public.users
  where id = p_user_id and active = true
  for share;

  if not found or v_user.role <> 'OBSERVER' then
    raise exception 'active observer account required';
  end if;

  select election_mode into v_mode
  from public.regional_settings
  where regional_office_id = v_user.regional_office_id;

  if v_mode <> 'VOTING' then
    raise exception 'participation unavailable outside VOTING phase';
  end if;

  select new_value into v_existing
  from public.participation_events
  where operation_uuid = p_operation_uuid;
  if found then return v_existing; end if;

  insert into public.participation_counters(local_bureau_id, current_count, updated_by)
  values(v_user.local_bureau_id, 0, v_user.id)
  on conflict (local_bureau_id) do nothing;

  select current_count into v_old
  from public.participation_counters
  where local_bureau_id = v_user.local_bureau_id
  for update;

  v_new := v_old + p_delta;
  if v_new < 0 then raise exception 'counter cannot be negative'; end if;

  begin
    insert into public.participation_events(
      operation_uuid, local_bureau_id, observer_id,
      previous_value, delta, new_value, device_id
    ) values (
      p_operation_uuid, v_user.local_bureau_id, v_user.id,
      v_old, p_delta, v_new, p_device_id
    );
  exception when unique_violation then
    select new_value into v_existing
    from public.participation_events
    where operation_uuid = p_operation_uuid;
    return v_existing;
  end;

  update public.participation_counters
  set current_count = v_new,
      updated_at = now(),
      updated_by = v_user.id
  where local_bureau_id = v_user.local_bureau_id;

  insert into public.observer_presence(observer_id, local_bureau_id, last_seen_at, connection_status, updated_at)
  values(v_user.id, v_user.local_bureau_id, now(), 'CONNECTED', now())
  on conflict (observer_id) do update
    set local_bureau_id = excluded.local_bureau_id,
        last_seen_at = excluded.last_seen_at,
        connection_status = 'CONNECTED',
        updated_at = now();

  insert into public.audit_logs(regional_office_id, user_id, action, entity_type, entity_id, metadata)
  values(
    v_user.regional_office_id,
    v_user.id,
    'PARTICIPATION_UPDATE',
    'local_bureau',
    v_user.local_bureau_id,
    jsonb_build_object(
      'delta', p_delta,
      'previous_value', v_old,
      'new_value', v_new,
      'operation_uuid', p_operation_uuid,
      'device_id', p_device_id
    )
  );

  return v_new;
end $$;

create or replace function public.heartbeat_observer(
  p_user_id uuid,
  p_connection_status text default 'CONNECTED'
) returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users;
  v_now timestamptz := now();
begin
  if p_connection_status not in ('CONNECTED','OFFLINE','BACKGROUND') then
    raise exception 'invalid connection status';
  end if;

  select * into v_user
  from public.users
  where id = p_user_id and active = true;

  if not found or v_user.role <> 'OBSERVER' then
    raise exception 'active observer account required';
  end if;

  insert into public.observer_presence(observer_id, local_bureau_id, last_seen_at, connection_status, updated_at)
  values(v_user.id, v_user.local_bureau_id, v_now, p_connection_status, v_now)
  on conflict (observer_id) do update
    set local_bureau_id = excluded.local_bureau_id,
        last_seen_at = excluded.last_seen_at,
        connection_status = excluded.connection_status,
        updated_at = excluded.updated_at;

  return v_now;
end $$;

create or replace function public.confirm_party_result(
  p_user_id uuid,
  p_votes integer,
  p_operation_uuid uuid
) returns public.party_results
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users;
  v_mode public.election_mode;
  v_result public.party_results;
begin
  if p_votes < 0 or p_votes > 1000000 then raise exception 'votes out of range'; end if;

  select * into v_user
  from public.users
  where id = p_user_id and active = true;

  if not found or v_user.role <> 'OBSERVER' then
    raise exception 'active observer account required';
  end if;

  select election_mode into v_mode
  from public.regional_settings
  where regional_office_id = v_user.regional_office_id;
  if v_mode <> 'COUNTING' then
    raise exception 'result submission unavailable outside COUNTING phase';
  end if;

  select * into v_result
  from public.party_results
  where operation_uuid = p_operation_uuid;
  if found then return v_result; end if;

  if exists(select 1 from public.party_results where local_bureau_id = v_user.local_bureau_id) then
    raise exception 'result already confirmed for local bureau';
  end if;

  insert into public.party_results(
    operation_uuid, local_bureau_id, observer_id, votes,
    status, submitted_at, confirmed_at, updated_at
  ) values (
    p_operation_uuid, v_user.local_bureau_id, v_user.id, p_votes,
    'CONFIRMED', now(), now(), now()
  ) returning * into v_result;

  insert into public.audit_logs(regional_office_id, user_id, action, entity_type, entity_id, metadata)
  values(
    v_user.regional_office_id,
    v_user.id,
    'RESULT_CONFIRMATION',
    'party_result',
    v_result.id,
    jsonb_build_object('votes', p_votes, 'local_bureau_id', v_user.local_bureau_id, 'operation_uuid', p_operation_uuid)
  );

  return v_result;
end $$;

create or replace function public.request_result_correction(
  p_user_id uuid,
  p_result_id uuid,
  p_proposed_votes integer,
  p_reason text
) returns public.result_corrections
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users;
  v_result public.party_results;
  v_bureau public.local_bureaus;
  v_correction public.result_corrections;
begin
  if p_proposed_votes < 0 or p_proposed_votes > 1000000 then raise exception 'votes out of range'; end if;
  if char_length(trim(p_reason)) < 3 then raise exception 'correction reason required'; end if;

  select * into v_user from public.users where id = p_user_id and active = true;
  if not found then raise exception 'active application user required'; end if;

  select * into v_result from public.party_results where id = p_result_id;
  if not found then raise exception 'result not found'; end if;

  select * into v_bureau from public.local_bureaus where id = v_result.local_bureau_id;
  if v_bureau.regional_office_id <> v_user.regional_office_id then
    raise exception 'result outside regional office';
  end if;

  if v_user.role = 'OBSERVER' and v_user.local_bureau_id <> v_result.local_bureau_id then
    raise exception 'observer cannot correct another local bureau';
  end if;

  if exists(select 1 from public.result_corrections where result_id = p_result_id and status = 'PENDING') then
    raise exception 'a correction request is already pending';
  end if;

  insert into public.result_corrections(
    result_id, old_value, proposed_value, reason, requested_by
  ) values (
    p_result_id, v_result.votes, p_proposed_votes, trim(p_reason), v_user.id
  ) returning * into v_correction;

  update public.party_results
  set status = 'CORRECTION_PENDING', updated_at = now()
  where id = p_result_id;

  insert into public.audit_logs(regional_office_id, user_id, action, entity_type, entity_id, metadata)
  values(
    v_user.regional_office_id,
    v_user.id,
    'CORRECTION_REQUEST',
    'party_result',
    p_result_id,
    jsonb_build_object('old_value', v_result.votes, 'proposed_value', p_proposed_votes, 'reason', trim(p_reason))
  );

  return v_correction;
end $$;

create or replace function public.resolve_result_correction(
  p_user_id uuid,
  p_correction_id uuid,
  p_approve boolean
) returns public.result_corrections
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin public.users;
  v_correction public.result_corrections;
  v_result public.party_results;
  v_bureau public.local_bureaus;
begin
  select * into v_admin
  from public.users
  where id = p_user_id and active = true and role = 'REGIONAL_ADMIN';
  if not found then raise exception 'regional admin required'; end if;

  select * into v_correction
  from public.result_corrections
  where id = p_correction_id
  for update;
  if not found then raise exception 'correction not found'; end if;
  if v_correction.status <> 'PENDING' then raise exception 'correction already resolved'; end if;

  select * into v_result from public.party_results where id = v_correction.result_id;
  select * into v_bureau from public.local_bureaus where id = v_result.local_bureau_id;
  if v_bureau.regional_office_id <> v_admin.regional_office_id then
    raise exception 'correction outside regional office';
  end if;

  if p_approve then
    update public.party_results
    set votes = v_correction.proposed_value,
        status = 'CORRECTED',
        updated_at = now()
    where id = v_correction.result_id;

    update public.result_corrections
    set status = 'APPROVED', validated_by = v_admin.id, resolved_at = now()
    where id = p_correction_id
    returning * into v_correction;
  else
    update public.party_results
    set status = 'CONFIRMED', updated_at = now()
    where id = v_correction.result_id;

    update public.result_corrections
    set status = 'REJECTED', validated_by = v_admin.id, resolved_at = now()
    where id = p_correction_id
    returning * into v_correction;
  end if;

  insert into public.audit_logs(regional_office_id, user_id, action, entity_type, entity_id, metadata)
  values(
    v_admin.regional_office_id,
    v_admin.id,
    case when p_approve then 'CORRECTION_APPROVED' else 'CORRECTION_REJECTED' end,
    'result_correction',
    p_correction_id,
    jsonb_build_object('result_id', v_correction.result_id)
  );

  return v_correction;
end $$;

create or replace function public.set_election_mode(
  p_user_id uuid,
  p_mode public.election_mode
) returns public.election_mode
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin public.users;
begin
  select * into v_admin
  from public.users
  where id = p_user_id and active = true and role = 'REGIONAL_ADMIN';
  if not found then raise exception 'regional admin required'; end if;

  insert into public.regional_settings(regional_office_id, election_mode, updated_at)
  values(v_admin.regional_office_id, p_mode, now())
  on conflict (regional_office_id) do update
    set election_mode = excluded.election_mode,
        updated_at = now();

  insert into public.audit_logs(regional_office_id, user_id, action, entity_type, metadata)
  values(v_admin.regional_office_id, v_admin.id, 'ELECTION_MODE_CHANGED', 'regional_setting', jsonb_build_object('mode', p_mode));

  return p_mode;
end $$;

commit;
-- FINAL V3 SECURITY + REALTIME
-- The browser never receives a Supabase secret/publishable key for business data.
-- All business access goes through the backend with its own application JWT.
-- RLS is enabled with no anon/authenticated policies; service_role remains server-only.

begin;

alter table public.regional_offices enable row level security;
alter table public.regional_settings enable row level security;
alter table public.local_bureaus enable row level security;
alter table public.users enable row level security;
alter table public.user_sessions enable row level security;
alter table public.participation_counters enable row level security;
alter table public.participation_events enable row level security;
alter table public.observer_presence enable row level security;
alter table public.party_results enable row level security;
alter table public.result_corrections enable row level security;
alter table public.audit_logs enable row level security;

-- No browser role may access business tables directly.
revoke all on public.regional_offices from anon, authenticated;
revoke all on public.regional_settings from anon, authenticated;
revoke all on public.local_bureaus from anon, authenticated;
revoke all on public.users from anon, authenticated;
revoke all on public.user_sessions from anon, authenticated;
revoke all on public.participation_counters from anon, authenticated;
revoke all on public.participation_events from anon, authenticated;
revoke all on public.observer_presence from anon, authenticated;
revoke all on public.party_results from anon, authenticated;
revoke all on public.result_corrections from anon, authenticated;
revoke all on public.audit_logs from anon, authenticated;

revoke all on function public.confirm_participation_delta(uuid, integer, uuid, text) from public, anon, authenticated;
revoke all on function public.heartbeat_observer(uuid, text) from public, anon, authenticated;
revoke all on function public.confirm_party_result(uuid, integer, uuid) from public, anon, authenticated;
revoke all on function public.request_result_correction(uuid, uuid, integer, text) from public, anon, authenticated;
revoke all on function public.resolve_result_correction(uuid, uuid, boolean) from public, anon, authenticated;
revoke all on function public.set_election_mode(uuid, public.election_mode) from public, anon, authenticated;

grant all on public.regional_offices to service_role;
grant all on public.regional_settings to service_role;
grant all on public.local_bureaus to service_role;
grant all on public.users to service_role;
grant all on public.user_sessions to service_role;
grant all on public.participation_counters to service_role;
grant all on public.participation_events to service_role;
grant all on public.observer_presence to service_role;
grant all on public.party_results to service_role;
grant all on public.result_corrections to service_role;
grant all on public.audit_logs to service_role;

grant execute on function public.confirm_participation_delta(uuid, integer, uuid, text) to service_role;
grant execute on function public.heartbeat_observer(uuid, text) to service_role;
grant execute on function public.confirm_party_result(uuid, integer, uuid) to service_role;
grant execute on function public.request_result_correction(uuid, uuid, integer, text) to service_role;
grant execute on function public.resolve_result_correction(uuid, uuid, boolean) to service_role;
grant execute on function public.set_election_mode(uuid, public.election_mode) to service_role;

-- Realtime is consumed only by the backend service-role client, then re-broadcast
-- as authorization-neutral refresh notifications over the backend WebSocket.
alter table public.local_bureaus replica identity full;
alter table public.users replica identity full;
alter table public.participation_counters replica identity full;
alter table public.observer_presence replica identity full;
alter table public.party_results replica identity full;
alter table public.result_corrections replica identity full;
alter table public.regional_settings replica identity full;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='local_bureaus') then
    alter publication supabase_realtime add table public.local_bureaus;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='users') then
    alter publication supabase_realtime add table public.users;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='participation_counters') then
    alter publication supabase_realtime add table public.participation_counters;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='observer_presence') then
    alter publication supabase_realtime add table public.observer_presence;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='party_results') then
    alter publication supabase_realtime add table public.party_results;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='result_corrections') then
    alter publication supabase_realtime add table public.result_corrections;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='regional_settings') then
    alter publication supabase_realtime add table public.regional_settings;
  end if;
end $$;

commit;


-- ================================================================
-- V4 MULTI-CATEGORY RESULTS UPGRADE
-- ================================================================

-- V4 — résultats multi-catégories + téléphone visible côté monitoring
-- Conserve : regional_offices, local_bureaus, users, participation, presence, sessions, audit.
-- Remplace uniquement l'ancien modèle de résultat "un seul parti".
-- Catégories suivies : PAM, PI, RNI, PJD, USFP, MP, REJECTED.
-- IMPORTANT : aucun total général n'est calculé ni comparé à la participation.

begin;

-- Ancien modèle V3.
drop function if exists public.confirm_party_result(uuid, integer, uuid);
drop function if exists public.request_result_correction(uuid, uuid, integer, text);
drop function if exists public.request_result_correction(uuid, integer, text);
drop function if exists public.resolve_result_correction(uuid, uuid, boolean);
drop function if exists public.resolve_result_correction(uuid, boolean);

drop table if exists public.result_corrections cascade;
drop table if exists public.party_results cascade;

-- Catégories suivies. REJECTED n'est pas un parti politique : c'est une catégorie technique.
create table if not exists public.result_categories (
  code text primary key,
  label text not null,
  category_type text not null check (category_type in ('PARTY','REJECTED')),
  display_order integer not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.result_categories(code, label, category_type, display_order, active) values
  ('PAM', 'PAM', 'PARTY', 1, true),
  ('PI', 'PI', 'PARTY', 2, true),
  ('RNI', 'RNI', 'PARTY', 3, true),
  ('PJD', 'PJD', 'PARTY', 4, true),
  ('USFP', 'USFP', 'PARTY', 5, true),
  ('MP', 'MP', 'PARTY', 6, true),
  ('REJECTED', 'Rejetés / non comptabilisés', 'REJECTED', 7, true)
on conflict (code) do update set
  label = excluded.label,
  category_type = excluded.category_type,
  display_order = excluded.display_order,
  active = excluded.active;

-- Une transmission complète et définitive par bureau local.
create table public.bureau_result_submissions (
  id uuid primary key default gen_random_uuid(),
  operation_uuid uuid not null unique,
  local_bureau_id uuid not null unique references public.local_bureaus(id) on delete restrict,
  observer_id uuid not null references public.users(id) on delete restrict,
  status public.result_status not null default 'CONFIRMED',
  submitted_at timestamptz not null default now(),
  confirmed_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index bureau_result_submissions_status_idx on public.bureau_result_submissions(status);
create index bureau_result_submissions_observer_idx on public.bureau_result_submissions(observer_id);

-- Les 7 valeurs sont séparées et normalisées. Aucun champ total_votes n'existe volontairement.
create table public.bureau_result_values (
  submission_id uuid not null references public.bureau_result_submissions(id) on delete cascade,
  category_code text not null references public.result_categories(code) on delete restrict,
  votes integer not null check (votes >= 0 and votes <= 1000000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (submission_id, category_code)
);
create index bureau_result_values_category_idx on public.bureau_result_values(category_code);

-- Correction ciblée sur UNE catégorie d'une transmission.
create table public.result_corrections (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null,
  category_code text not null,
  old_value integer not null check (old_value >= 0),
  proposed_value integer not null check (proposed_value >= 0 and proposed_value <= 1000000),
  reason text not null check (char_length(trim(reason)) between 3 and 1000),
  requested_by uuid not null references public.users(id) on delete restrict,
  validated_by uuid references public.users(id) on delete restrict,
  status text not null default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  foreign key (submission_id, category_code)
    references public.bureau_result_values(submission_id, category_code)
    on delete restrict
);
create unique index one_pending_correction_per_submission_category
  on public.result_corrections(submission_id, category_code)
  where status = 'PENDING';
create index result_corrections_submission_idx on public.result_corrections(submission_id, created_at desc);

-- Enregistrement atomique des 7 valeurs.
create or replace function public.confirm_bureau_results(
  p_user_id uuid,
  p_operation_uuid uuid,
  p_results jsonb
) returns public.bureau_result_submissions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users;
  v_mode public.election_mode;
  v_submission public.bureau_result_submissions;
  v_category record;
  v_votes integer;
  v_expected_count integer;
  v_received_count integer;
begin
  if p_results is null or jsonb_typeof(p_results) <> 'object' then
    raise exception 'results must be a JSON object';
  end if;

  select * into v_user
  from public.users
  where id = p_user_id and active = true;

  if not found or v_user.role <> 'OBSERVER' then
    raise exception 'active observer account required';
  end if;

  select election_mode into v_mode
  from public.regional_settings
  where regional_office_id = v_user.regional_office_id;

  if v_mode <> 'COUNTING' then
    raise exception 'result submission unavailable outside COUNTING phase';
  end if;

  select * into v_submission
  from public.bureau_result_submissions
  where operation_uuid = p_operation_uuid;

  if found then
    if v_submission.observer_id <> v_user.id then
      raise exception 'operation uuid already used by another observer';
    end if;
    return v_submission;
  end if;

  if exists(select 1 from public.bureau_result_submissions where local_bureau_id = v_user.local_bureau_id) then
    raise exception 'results already confirmed for local bureau';
  end if;

  select count(*) into v_expected_count from public.result_categories where active = true;
  select count(*) into v_received_count from jsonb_object_keys(p_results);
  if v_received_count <> v_expected_count then
    raise exception 'exactly % result categories are required', v_expected_count;
  end if;

  -- Validation avant toute insertion. On ne calcule volontairement aucun total.
  for v_category in
    select code from public.result_categories where active = true order by display_order
  loop
    if not (p_results ? v_category.code) then
      raise exception 'missing result category: %', v_category.code;
    end if;

    if jsonb_typeof(p_results -> v_category.code) <> 'number' then
      raise exception 'result for % must be an integer', v_category.code;
    end if;

    begin
      v_votes := (p_results ->> v_category.code)::integer;
    exception when others then
      raise exception 'result for % must be an integer', v_category.code;
    end;

    if v_votes < 0 or v_votes > 1000000 then
      raise exception 'result for % out of range', v_category.code;
    end if;
  end loop;

  insert into public.bureau_result_submissions(
    operation_uuid, local_bureau_id, observer_id, status, submitted_at, confirmed_at, updated_at
  ) values (
    p_operation_uuid, v_user.local_bureau_id, v_user.id, 'CONFIRMED', now(), now(), now()
  ) returning * into v_submission;

  for v_category in
    select code from public.result_categories where active = true order by display_order
  loop
    v_votes := (p_results ->> v_category.code)::integer;
    insert into public.bureau_result_values(submission_id, category_code, votes)
    values(v_submission.id, v_category.code, v_votes);
  end loop;

  insert into public.audit_logs(regional_office_id, user_id, action, entity_type, entity_id, metadata)
  values(
    v_user.regional_office_id,
    v_user.id,
    'RESULT_CONFIRMATION',
    'bureau_result_submission',
    v_submission.id,
    jsonb_build_object(
      'local_bureau_id', v_user.local_bureau_id,
      'operation_uuid', p_operation_uuid,
      'results', p_results
    )
  );

  return v_submission;
end $$;

create or replace function public.request_result_correction(
  p_user_id uuid,
  p_submission_id uuid,
  p_category_code text,
  p_proposed_votes integer,
  p_reason text
) returns public.result_corrections
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users;
  v_submission public.bureau_result_submissions;
  v_bureau public.local_bureaus;
  v_current integer;
  v_correction public.result_corrections;
begin
  if p_proposed_votes < 0 or p_proposed_votes > 1000000 then raise exception 'votes out of range'; end if;
  if char_length(trim(p_reason)) < 3 then raise exception 'correction reason required'; end if;

  select * into v_user from public.users where id = p_user_id and active = true;
  if not found then raise exception 'active application user required'; end if;

  select * into v_submission from public.bureau_result_submissions where id = p_submission_id;
  if not found then raise exception 'result submission not found'; end if;

  select * into v_bureau from public.local_bureaus where id = v_submission.local_bureau_id;
  if v_bureau.regional_office_id <> v_user.regional_office_id then
    raise exception 'result outside regional office';
  end if;

  if v_user.role = 'OBSERVER' and v_user.local_bureau_id <> v_submission.local_bureau_id then
    raise exception 'observer cannot correct another local bureau';
  end if;

  select votes into v_current
  from public.bureau_result_values
  where submission_id = p_submission_id and category_code = p_category_code;
  if not found then raise exception 'result category not found'; end if;

  if exists(
    select 1 from public.result_corrections
    where submission_id = p_submission_id and category_code = p_category_code and status = 'PENDING'
  ) then
    raise exception 'a correction request is already pending for this category';
  end if;

  insert into public.result_corrections(
    submission_id, category_code, old_value, proposed_value, reason, requested_by
  ) values (
    p_submission_id, p_category_code, v_current, p_proposed_votes, trim(p_reason), v_user.id
  ) returning * into v_correction;

  update public.bureau_result_submissions
  set status = 'CORRECTION_PENDING', updated_at = now()
  where id = p_submission_id;

  insert into public.audit_logs(regional_office_id, user_id, action, entity_type, entity_id, metadata)
  values(
    v_user.regional_office_id,
    v_user.id,
    'CORRECTION_REQUEST',
    'bureau_result_submission',
    p_submission_id,
    jsonb_build_object(
      'category_code', p_category_code,
      'old_value', v_current,
      'proposed_value', p_proposed_votes,
      'reason', trim(p_reason)
    )
  );

  return v_correction;
end $$;

create or replace function public.resolve_result_correction(
  p_user_id uuid,
  p_correction_id uuid,
  p_approve boolean
) returns public.result_corrections
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin public.users;
  v_correction public.result_corrections;
  v_submission public.bureau_result_submissions;
  v_bureau public.local_bureaus;
  v_has_pending boolean;
  v_has_approved boolean;
begin
  select * into v_admin
  from public.users
  where id = p_user_id and active = true and role = 'REGIONAL_ADMIN';
  if not found then raise exception 'regional admin required'; end if;

  select * into v_correction
  from public.result_corrections
  where id = p_correction_id
  for update;
  if not found then raise exception 'correction not found'; end if;
  if v_correction.status <> 'PENDING' then raise exception 'correction already resolved'; end if;

  select * into v_submission
  from public.bureau_result_submissions
  where id = v_correction.submission_id;

  select * into v_bureau
  from public.local_bureaus
  where id = v_submission.local_bureau_id;

  if v_bureau.regional_office_id <> v_admin.regional_office_id then
    raise exception 'correction outside regional office';
  end if;

  if p_approve then
    update public.bureau_result_values
    set votes = v_correction.proposed_value, updated_at = now()
    where submission_id = v_correction.submission_id
      and category_code = v_correction.category_code;

    update public.result_corrections
    set status = 'APPROVED', validated_by = v_admin.id, resolved_at = now()
    where id = p_correction_id
    returning * into v_correction;
  else
    update public.result_corrections
    set status = 'REJECTED', validated_by = v_admin.id, resolved_at = now()
    where id = p_correction_id
    returning * into v_correction;
  end if;

  select exists(
    select 1 from public.result_corrections
    where submission_id = v_correction.submission_id and status = 'PENDING'
  ) into v_has_pending;

  select exists(
    select 1 from public.result_corrections
    where submission_id = v_correction.submission_id and status = 'APPROVED'
  ) into v_has_approved;

  update public.bureau_result_submissions
  set status = case
        when v_has_pending then 'CORRECTION_PENDING'::public.result_status
        when v_has_approved then 'CORRECTED'::public.result_status
        else 'CONFIRMED'::public.result_status
      end,
      updated_at = now()
  where id = v_correction.submission_id;

  insert into public.audit_logs(regional_office_id, user_id, action, entity_type, entity_id, metadata)
  values(
    v_admin.regional_office_id,
    v_admin.id,
    case when p_approve then 'CORRECTION_APPROVED' else 'CORRECTION_REJECTED' end,
    'result_correction',
    p_correction_id,
    jsonb_build_object(
      'submission_id', v_correction.submission_id,
      'category_code', v_correction.category_code,
      'old_value', v_correction.old_value,
      'proposed_value', v_correction.proposed_value
    )
  );

  return v_correction;
end $$;

-- Accès : le frontend ne parle jamais directement à ces tables.
alter table public.result_categories enable row level security;
alter table public.bureau_result_submissions enable row level security;
alter table public.bureau_result_values enable row level security;
alter table public.result_corrections enable row level security;

revoke all on public.result_categories from anon, authenticated;
revoke all on public.bureau_result_submissions from anon, authenticated;
revoke all on public.bureau_result_values from anon, authenticated;
revoke all on public.result_corrections from anon, authenticated;

revoke all on function public.confirm_bureau_results(uuid, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.request_result_correction(uuid, uuid, text, integer, text) from public, anon, authenticated;
revoke all on function public.resolve_result_correction(uuid, uuid, boolean) from public, anon, authenticated;

grant all on public.result_categories to service_role;
grant all on public.bureau_result_submissions to service_role;
grant all on public.bureau_result_values to service_role;
grant all on public.result_corrections to service_role;

grant execute on function public.confirm_bureau_results(uuid, uuid, jsonb) to service_role;
grant execute on function public.request_result_correction(uuid, uuid, text, integer, text) to service_role;
grant execute on function public.resolve_result_correction(uuid, uuid, boolean) to service_role;

-- Realtime côté backend Supabase -> WebSocket applicatif.
alter table public.bureau_result_submissions replica identity full;
alter table public.bureau_result_values replica identity full;
alter table public.result_corrections replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='bureau_result_submissions'
  ) then
    alter publication supabase_realtime add table public.bureau_result_submissions;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='bureau_result_values'
  ) then
    alter publication supabase_realtime add table public.bureau_result_values;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='result_corrections'
  ) then
    alter publication supabase_realtime add table public.result_corrections;
  end if;
end $$;

commit;
